### ISSUE TITLE
Unify configuration file handling 

### ISSUE THREAD

**Issue by pgrzesik** [serverless/utils#69]
Proposal of implementation/extension of existing `config.js` module so it covers all use cases currently supported by [platform-sdk](https://github.com/serverless/platform-sdk). It is a part of initiative: https://github.com/serverless/enterprise-plugin/issues/464

1. Get rid of merging config with `rc` utility. Reasoning: At the moment, in `utils`, when resolving config, we're using `rc` to read both `local` and `global` config files and merge them with `local` config overwriting `global`. This creates a situation where reading config after saving it can produce inconsistent results due to the fact that we're always saving to `global` - if saved property also exist in local config, it will be shadowed by that value when reading configuration. (Please correct me if I'm wrong here)
2. Introduce a method that will resolve the configuration file, resembling https://github.com/serverless/platform-sdk/blob/master/src/utils/configFile.js#L21 and always use it to resolve the config path when reading/writing. This will ensure that read-after-write will be always consistent and we won't run into situation as highlighted in 1.
3. Add `getLoggedInUser` util that will retrieve logged in user data - similar to https://github.com/serverless/platform-sdk/blob/master/src/utils/configFile.js#L80
4. Use it both in `components` and `enterprise-plugin`. 

I'd love to get your opinion on this one @medikoo, thanks in advance :bow:

**Comment by medikoo** [comment]
Thanks @pgrzesik! I have some concerns towards 1 & 2:

At first glance it seems to make sense. Still when I think of some use cases it seems that current behavior is desired.
I imagine a situation where in global config we have set some general settings, e.g. that we don't want the analytics to be sent, while local config is more about service affecting config (e.g. access key to dashboard).
If we will not merge the configs, in above setup it may create a situation where analytics are being sent as user didn't opt out in local config.

What we probably could do to improve the situation is to issue a warning when user attempts to write to global config a property that we see is shadowed by different value in local config.

**Comment by pgrzesik** [comment]
Thanks @medikoo for quick response. I'm not 100% sure what is the actual use case for local vs global config, but it seems like currently in `platform-sdk` (and by dependency in `enterprise-plugin` and `components`), we use only one config at a time - if local is present, only that config is used both for reading and writing. Changing the logic to always write to global and merge config on reads is breaking current functionality. Do you know the reasoning behind current approach in `enterprise-plugin` and `components` or maybe you have an idea who would be a good person to ask that question?

**Comment by medikoo** [comment]
> Do you know the reasoning behind current approach in `enterprise-plugin` and `components` 

When `login` and `logout` were introduced any so far config handling was baked into Framework, there was no external util  which SDK could use (it's recently where we secluded this logic to `@serverless/utils`).

I believe then someone quickly patched new config handler in context of SDK that didn't imply using `.rc` (I assume simply to not add an extra dependency), but resorted just to `./` and `~/`.

Anyway, you've put light on quite important behavior, I was not fully aware of. In case of login, logout it makes a big sense to store authentication to service specific config (if it exists), as thanks to that user may use different authentication per service. So I totally agree that we should maintain that.

I think it's fine to get rid of `rc` (I think it does too much). Still aside of resolving config from `./` and `~/`, `rc` also I think looks into `~/.config/`, and I think it would be nice to keep support for that location (check https://github.com/serverless/utils/issues/58).

As I think of it, our API should probably work that way:

1. `getConfig` or `get` - Resolve _local_ (if it exists) and _global_ (either from `~/` or `~/.config`). If both exist it should return deep merged result of _local_ and _global_, with _local_ settings shadowing _global_ (we should also probably show warning if we detect that config exists at both `~/` and `~/.config` locations)
2. `getGlobalConfig` - Ditch in favor of `getConfig`
3. `set` - Save. If _local_ config exists save to _local_. Otherwise if `~/.config` exists` save to it. If not then save to `~/`
4. `setGlobal` - If `~/.config` exists` save to it. If not then save to `~/`

What do you think?

**Comment by pgrzesik** [comment]
Thanks @medikoo, especially for mentioning support for `~/.config` as well. I believe merging configs will be safe as long as local config will override global one during merge. :+1:

**Comment by pgrzesik** [comment]
During implementation, I've started having some doubts about merging configs while retrieving them. Let me explain why - the problematic situation happens during current use cases, where in some cases config is retrieved, modified, and saved back as a whole. When we allow such patterns with merging conflicts, we will quickly move all properties from global to local configuration on first save, because during save, all merged properties will land in a local file. Example:

```
local = {a: 1}
global = {b: 1}
```
when we would merge them, we would end up with `{a: 1, b: 1}`, but when we save it back, local config will be set to `{a: 1, b: 1}` and I'm not sure if that's the intended behavior. One option is to limit updates to specific keys, but that seems prohibitive.

Due to that, I'm leaning towards the approach of using only one config file (if local is present, only use data from local file), otherwise we end up in a situation where after one save, local configuration is de facto only source of truth if it's present (e.g. if e.g. you have a flag in global config file but later you want to change it, you will have to manually update that in local config files, because the previous version of that flag was already written to local file and will shadow the global setting). 

What do you think @medikoo ?

Also a note on `~/.config` support - if we'd like to support all `rc`-supported locations, we would have to handle way more than that as it searches more locations than just that (see: https://github.com/dominictarr/rc#standards). I think if we would like to support custom config locations, we should expose it via some kind of flag or environment variable. 

What do you think?

**Comment by medikoo** [comment]
> When we allow such patterns with merging conflicts, we will quickly move all properties from global to local configuration on first save

As I think of it, we should never extend the _merged_ config in `set`. It's either _local_ or _global_ config that should be extended.

Technically _read_ operation returns merged config, but _write_ operation extends just one of the configs and it should not be affected by merging that happens on _read_.

> Also a note on ~/.config support - if we'd like to support all rc-supported locations, we would have to handle way more than that as it searches more locations than just that (see: https://github.com/dominictarr/rc#standards).

That's a very good point. This also brings to light, that by supporting _merged_ configs we're sort of going our way.

Still my opinion is, that it'll be good to break with `rc` module, and introduce a more stricter rules. `rc` design seems to be too permissive (I remember having some wierd behaviors in tests due to its searching parent dirs all the way up) also fact that it mixes config properties with its meta properties (resolved config locations) lights a red bulb in my head. It's also no longer maintained project, from very early Node.js days.

So I'd stick to supporting just `~/` and `~/.config`as _global_ and `./` as _local_. I think it should play best in our case.

I think not supporting _parent_ directories of current working directory, `~/.serverless/config` and `/etc/serverless` can be considered as security improvement.

What do you think?

**Comment by pgrzesik** [comment]
> As I think of it, we should never extend the _merged_ config in `set`. It's either _local_ or _global_ config that should be extended.

I agree here. With my current WIP implementation, I went this way - on `set`, I'm fetching only one config without merging and extending this one and I think that's the best way to approach it :+1: 

> Still my opinion is, that it'll be good to break with rc module, and introduce a more stricter rules. rc design seems to be too permissive (I remember having some wierd behaviors in tests due to its searching parent dirs all the way up) also fact that it mixes config properties with its meta properties (resolved config locations) lights a red bulb in my head. It's also no longer maintained project, from very early Node.js days.

So I'd stick to supporting just ~/ and ~/.configas global and ./ as local. I think it should play best in our case.

In current implementation I temporarily skipped support for `~/.config`, but I don't see a problem with supporting it after all, with `~/` having higher priority when for some reason we encounter both.
